-- Align two check constraints with the values the application actually writes.
--
-- Both were wrong from the initial schema and neither could be caught there,
-- because nothing wrote to these tables until Phase 4. The RLS tests inserted
-- rows they chose the values for, so they agreed with the schema rather than
-- with the code — which is the failure mode of a fixture that is written to
-- fit the thing it is testing.
--
-- The source of truth for both is TypeScript:
--   messages.type  -> chatResponseSchema in src/lib/schemas/ai.ts
--   *.mode         -> StoredSynthesis / StoredMeditation / StoredComparison

-- 'clarification' was invented here. The schema says 'clarifying_question',
-- and it is one of the four response types the chat prompt is built around.
alter table public.messages drop constraint messages_type_check;
alter table public.messages add constraint messages_type_check
  check (type in ('reflection', 'recommendation', 'clarifying_question', 'crisis'));

-- 'byok' is still a live value: the pasted-key path exists until Phase 5
-- deletes it, and rows written before then keep saying so. Narrowing this to
-- ('fixture', 'server') is part of that phase, not a thing to assume early —
-- a stored synthesis generated with somebody's own key is not a synthesis
-- generated by the server, and the record should not claim it was.
alter table public.soul_map_syntheses drop constraint soul_map_syntheses_mode_check;
alter table public.soul_map_syntheses add constraint soul_map_syntheses_mode_check
  check (mode in ('fixture', 'byok', 'server'));

alter table public.meditations drop constraint meditations_mode_check;
alter table public.meditations add constraint meditations_mode_check
  check (mode in ('fixture', 'byok', 'server'));

alter table public.chart_comparisons drop constraint chart_comparisons_mode_check;
alter table public.chart_comparisons add constraint chart_comparisons_mode_check
  check (mode in ('fixture', 'byok', 'server'));

-- Constrained now that the value domain is settled. IdeationAnswer in
-- src/lib/safety.ts; 'plan_o_intencion' is the one the deterministic scan
-- treats as high severity without reading any text.
alter table public.clients add constraint clients_ideation_check
  check (clinical_ideation_6m is null
         or clinical_ideation_6m in ('no', 'fugaces_sin_plan', 'frecuentes', 'plan_o_intencion'));

alter table public.anonymous_sessions add constraint anonymous_sessions_ideation_check
  check (clinical_ideation_6m is null
         or clinical_ideation_6m in ('no', 'fugaces_sin_plan', 'frecuentes', 'plan_o_intencion'));

-- Newly constrained rather than corrected: category was plain text. PDR 5.9
-- lists five; `indirecto` is the sixth, added by src/lib/safety.ts for the
-- low-severity band that fires on oblique phrasing.
alter table public.crisis_events add constraint crisis_events_category_check
  check (category in ('ideacion', 'autolesion', 'abuso', 'psicosis', 'panico', 'indirecto'));
